/*
 * SPI_Basics(328p).c
 *
 * Created: 22/08/2020 09:56:26
 * Author : mituki
 */ 

/*
This programming task brings to light the very basic principles or concepts of SPI communication in the Atmega 328p
micro controller..Most of the information and programming is adapted from the Atmega 328p data sheet, SPI section.
SPI(Serial Peripheral Interface) is a full duplex asynchronous communication for data transfer between micro controller
and external peripherals such as sensors,display modules etc. Full duplex to mean that data can be transferred in either
direction and synchronous in that both entities i.e micro controller and peripheral have to share a common clock signal
which for this case is generated by the master..Master is a terminology used to refer to the transmitting entity in the
configuration.

SPI is configuration takes two devices whereby one of them is a master and the other a slave..The master generates the clock 
signal and transmits data to the slave..SPI can theoretically have one master and infinite slaves but practically the slaves 
are limited by electronics principles.

There are four "wires" involved in an SPI setup.These are are:-
	PIN		ATMEGA328				DESCRIPTION
	MOSI	PB3						Master Out Slave In				Transfers data from the master to slave
	MISO	PB4						Master In Slave Out				Transfers data from the slave to the master
	SCK		PB5						Serial Clock					Clock signal generated by the master
	SS		PB2						Slave Select					Selects individual slave in multi slave set up.
	
*******much of the description on the same can be found on the Atmega328p data sheet****************************************  


*****************************************ATMEGA328P Specific content********************************************************
REGISTER DESCRIPTION
There are three registers on the Atmega328p which handle SPI communication:-
	1.SPCR0		SPI Control Register
	2.SPSR0		SPI Status Register
	3.SPDR0		SPI Data Register
	
1.SPCR0
8 bit register that controls the set up of SPI.All 8 bits are configurable in either read or write mode to manage the operation
of the SPI.
*******Bit Description********
BIT		7				6				5				4				3				2				1				0
Name	SPIE0			SPE0			DORD0			MSTR0			CPOL0			CPHA0			SPRO1			SPRO0
The functionality of the register bits clearly described in the data sheet

2.SPSR0
8 bit register but only 3 bits are considered. i.e bits 0,6,7 
BIT		7				6				0
NAME	SPIF0			WCOL0			SPI2x0

3.SPRDR0
8 bit data register.
*/
/*
****DESIGN TASK****
Initialize two Atmega328p micro controllers as master and slave respectively and transfer data from one to the other to control the
other to control the brightness of an LED using PMW..In simple terms the data is used to adjust duty cycle for the PWM. Twe will 
need two programs.For this program, we will configure the master.
*/


//SPI Master
#include <avr/io.h>
#include <util/delay.h>

#define F_CPU 16000000UL


void master_init(){
	//set MOSI,SCK,SS output mode
	DDRB |= ((1<<PORTB3) |(1<<PORTB5)|(1<<PORTB2));
	
	//set SS high(SS is active low i.e it is pulled low to select the slave to transmit to)
	PORTB |= (1<<PORTB2);
	
	//set enable for SPI operations'
	SPCR |= (1<<SPE);
	
	//configure SPI to master mode
	SPCR |= (1<<MSTR);
	
	//configure the master clock rate...(its very important to refer to data sheet)
	SPCR |= (1<<SPDR0);
	//f/64 == SCK clock
}

void master_transmit(uint8_t data){
	//pull SS low
	PORTB &=~(1<<PORTB2);
	
	//place data on data register
	SPDR = data;
	
	//wait for transmission to complete
	while(!(SPSR &(1<<SPIF)));
	
	//pull SS high
	PORTB |= (1<<PORTB2);
}


int main(void)
{
    /* Replace with your application code */
	master_init();
	uint8_t data = 0;
    while (1) 
    {
		master_transmit(data);
		data +=10;
		_delay_ms(2000);
    }
}

